#lang racket

(define (atom? x)
  (and (not (pair? x)) (not (null? x))))

(atom? '())
(atom? (quote ()))
(atom? (quote atom))
(atom? 'atom)
(atom? 'turkey)
(atom? '1492)
(atom? 'u)
(atom? '*abc$)
(list? '(atom))
;(list? '(atom turkey) 'or)
(list? '((atom turkey) or))

(null? '())
(null? '(77))
(zero? 0)
(zero? 9)
(define l1 (list '(+ 1 1) 7))
(define l2 (list 7 '(+ 1 1)))
(atom? (car l1))
(atom? (car l2))
